### ISSUE TITLE
Drifting after turning a large yaw

### ISSUE THREAD

**Issue by Dxxventi** [AIS-Bonn/attitude_estimator#2]
Hi, Did you have the drifting problem after turning an IMU with a large and yaw and turning it back to the original orientation? My IMU has only gyro and accelerometer, no magnetometer. All the 6 readings are around 0 when the IMU is static. What I did was: 
1) Keep IMU static, start the program, no drift
2) Turn the IMU around the up axis to a large angle, e.g. more than 90 degree, the output follows
3) Turn the IMU back to the original angle, the output follows
4) Keep the IMU static, the output starts to increase/decrease at a certain slope. The drift is very obvious.

**Comment by pallgeuer** [comment]
Hi, as you have no magnetometer, drift cannot totally be avoided because there is no information from the sensors that let's it do that. If you're not looking for an estimate of the yaw, but are interested in pitch and roll, then the output pitch and roll will still always be accurate.
If you are interested in yaw measurements as well, to almost entirely eliminate the drift you can turn up the Ti (integral time constant) to 1e12 (i.e. infinity), take the Kp gain down to something like 0.4, and implement a gyro autocalibration scheme whereby the gyro bias is automatically updated using low pass filtering whenever the gyro is stable for a few seconds or more. Using a carefully constructed method as such, I am able to achieve <0.01 deg/s drift (when stationary) with very cheap/noisy sensors. The gyro autocalibration scheme is not easy to describe in a few sentences, but is implemented in:
https://github.com/AIS-Bonn/humanoid_op_ros/blob/master/src/nimbro/hardware/nimbro_op_interface/src/robotinterface.cpp#L1478
Hope that helps,
Philipp


----- Original Message -----

**Comment by Dxxventi** [comment]
> Hi, as you have no magnetometer, drift cannot totally be avoided because there is no information from the sensors that let's it do that. If you're not looking for an estimate of the yaw, but are interested in pitch and roll, then the output pitch and roll will still always be accurate. If you are interested in yaw measurements as well, to almost entirely eliminate the drift you can turn up the Ti (integral time constant) to 1e12 (i.e. infinity), take the Kp gain down to something like 0.4, and implement a gyro autocalibration scheme whereby the gyro bias is automatically updated using low pass filtering whenever the gyro is stable for a few seconds or more. Using a carefully constructed method as such, I am able to achieve <0.01 deg/s drift (when stationary) with very cheap/noisy sensors. The gyro autocalibration scheme is not easy to describe in a few sentences, but is implemented in: https://github.com/AIS-Bonn/humanoid_op_ros/blob/master/src/nimbro/hardware/nimbro_op_interface/src/robotinterface.cpp#L1478 Hope that helps, Philipp
> […](#)
> ----- Original Message ----- From: "Dxxventi" <notifications@github.com> To: "AIS-Bonn/attitude_estimator" <attitude_estimator@noreply.github.com> Cc: "Subscribed" <subscribed@noreply.github.com> Sent: Thursday, 16 January, 2020 11:41:57 PM Subject: [AIS-Bonn/attitude_estimator] Drifting after turning a large yaw (#2) Hi, Did you have the drifting problem after turning an IMU with a large and yaw and turning it back to the original orientation? My IMU has only gyro and accelerometer, no magnetometer. All the 6 readings are around 0 when the IMU is static. What I did was: 1) Keep IMU static, start the program, no drift 2) Turn the IMU around the up axis to a large angle, e.g. more than 90 degree, the output follows 3) Turn the IMU back to the original angle, the output follows 4) Keep the IMU static, the output starts to increase/decrease at a certain slope. The drift is very obvious.
> -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #2

Thanks. This is really helpful. I will try it out.
